// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import { AuthProvider } from "@/context/AuthContext";
// import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col bg-white text-black dark:bg-gray-900 dark:text-white transition-colors duration-300">
       

//         {/* <main className="flex-grow container mx-auto px-4 py-8">
//           {children}
//         </main> */}

//         <AuthProvider>
//            <Navbar />
//           {children}
//             <Toaster position="top-right" />
//           </AuthProvider>

//         <Footer />
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MainNavbar } from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from '@/context/AuthContext';
import QueryProvider from '@/providers/QueryProvider';


const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata = {
  title: 'MediQueue',
  description: 'Tutor Booking System',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased light`} data-theme="light" suppressHydrationWarning>
      <body className="min-h-full flex flex-col bg-slate-50 text-slate-900 font-sans">
        
        {/* AuthProvider এবং QueryProvider সবার উপরে থাকতে হবে */}
        <AuthProvider>
          <QueryProvider>
            
            <MainNavbar />
            <main className="grow">
              {children}
            </main>
            <Footer />
            <Toaster position="top-right" />
            
          </QueryProvider>
        </AuthProvider>

      </body>
    </html>
  );
}